// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: extensions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Momento.Protos.Extensions {

  /// <summary>Holder for reflection information generated from extensions.proto</summary>
  public static partial class ExtensionsReflection {

    #region Descriptor
    /// <summary>File descriptor for extensions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExtensionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBleHRlbnNpb25zLnByb3RvGiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRv",
            "ci5wcm90byowCg1SZXRyeVNlbWFudGljEhAKDE5vdFJldHJ5YWJsZRAAEg0K",
            "CVJldHJ5YWJsZRABOkkKDnJldHJ5X3NlbWFudGljEh8uZ29vZ2xlLnByb3Rv",
            "YnVmLk1lc3NhZ2VPcHRpb25zGNCGAyABKA4yDi5SZXRyeVNlbWFudGljQl8K",
            "D2dycGMuZXh0ZW5zaW9uc1owZ2l0aHViLmNvbS9tb21lbnRvaHEvY2xpZW50",
            "LXNkay1nbztjbGllbnRfc2RrX2dvqgIZTW9tZW50by5Qcm90b3MuRXh0ZW5z",
            "aW9uc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Momento.Protos.Extensions.RetrySemantic), }, new pb::Extension[] { ExtensionsExtensions.RetrySemantic }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of extensions.proto</summary>
  public static partial class ExtensionsExtensions {
    /// <summary>
    /// Can this message be re-driven without an error?
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::Momento.Protos.Extensions.RetrySemantic> RetrySemantic =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::Momento.Protos.Extensions.RetrySemantic>(50000, pb::FieldCodec.ForEnum(400000, x => (int) x, x => (global::Momento.Protos.Extensions.RetrySemantic) x, global::Momento.Protos.Extensions.RetrySemantic.NotRetryable));
  }

  #region Enums
  /// <summary>
  /// A hint so you can decide a little more in the abstract "can this be retried?""
  /// </summary>
  public enum RetrySemantic {
    /// <summary>
    /// Never retry this message without telling the user. (you should infer this as the default)
    /// </summary>
    [pbr::OriginalName("NotRetryable")] NotRetryable = 0,
    /// <summary>
    /// You can retry this without surfacing an error to the user.
    /// </summary>
    [pbr::OriginalName("Retryable")] Retryable = 1,
  }

  #endregion

}

#endregion Designer generated code
